

# This file was *autogenerated* from the file find_order.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_10 = Integer(10); _sage_const_9 = Integer(9); _sage_const_8 = Integer(8); _sage_const_7 = Integer(7); _sage_const_6 = Integer(6); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_3 = Integer(3); _sage_const_1 = Integer(1)
w = PolynomialRing(GF(_sage_const_2 ), 'x')
x = w.gen()
f = x**_sage_const_10  + x**_sage_const_9  + x**_sage_const_8  + x**_sage_const_7  + x**_sage_const_6  + x**_sage_const_5  + x**_sage_const_4  + x**_sage_const_3  + x**_sage_const_2  + x**_sage_const_1  +_sage_const_1 

print("x is:", x)
print(type(x))
print("f is:", f)
print(type(f))
Fq = GF(_sage_const_2 **_sage_const_10 , 'a', modulus=f)
a = Fq.gen() 
g = a**_sage_const_9  + a**_sage_const_5  + a**_sage_const_4  + a**_sage_const_3  + _sage_const_1 

i = _sage_const_1 
while True:
    if g**i == _sage_const_1 :
        print("the order is: ", i)
        break
    i += _sage_const_1 

