

# This file was *autogenerated* from the file pohlig_hellman.sage
from sage.all_cmdline import *   # import sage library

_sage_const_20000000000 = Integer(20000000000); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_0 = Integer(0); _sage_const_1019 = Integer(1019); _sage_const_7 = Integer(7); _sage_const_1001 = Integer(1001); _sage_const_1879 = Integer(1879); _sage_const_11 = Integer(11); _sage_const_1236 = Integer(1236); _sage_const_2029 = Integer(2029); _sage_const_819 = Integer(819); _sage_const_160079 = Integer(160079); _sage_const_17 = Integer(17); _sage_const_66133 = Integer(66133); _sage_const_161386420777 = Integer(161386420777); _sage_const_10 = Integer(10); _sage_const_148775913664 = Integer(148775913664); _sage_const_599939 = Integer(599939); _sage_const_93522 = Integer(93522); _sage_const_10192004369 = Integer(10192004369); _sage_const_7198247104 = Integer(7198247104)
def pohlig_hellman(p: int, g: int, h: int)->int:
    MAX_PRIME_DIVISOR = _sage_const_20000000000  
    order = p-_sage_const_1 
    facs = (order).factor()
    B = max(MAX_PRIME_DIVISOR,floor((_sage_const_2 /_sage_const_3 ) * p))
    if facs[-_sage_const_1 ][_sage_const_0 ] >= B:
        print("The input is not doable, terminating...")
        return -_sage_const_1 

    print("The prime factors are: ", facs)
    bits = []
    #f is factor, e is exponent
    for f,e in facs:
        bits_0 = []
        bit1_0 = _sage_const_0 
        lhs = power_mod(h,order//f,p)  
        while lhs != power_mod(g,(order//f)*bit1_0,p):
            bit1_0 += _sage_const_1 
        bits_0.append(bit1_0)
        for i in srange(_sage_const_1 ,e):
            bitK_0 = _sage_const_0 
            bits_power = _sage_const_0 
            for j,b in enumerate(bits_0):  
                bits_power += power_mod(f,j,p)*b 
            fe = power_mod(f,i+_sage_const_1 ,p)
            lhs = power_mod(h,order//fe,p)
            rhs_partial = power_mod(g,(order//fe) * bits_power,p)
            while lhs!= (rhs_partial * power_mod(power_mod(g,order//f,p),bitK_0,p))% p:
                bitK_0 += _sage_const_1 
            bits_0.append(bitK_0)
        bitK = _sage_const_0 
        for i,b in enumerate(bits_0):
            
             bitK += b * power_mod(f,i,p)
        bits.append(bitK)
    # 
    #for the sake of conveniece, i will create a list of factors
    # which add any repeated factors as one proper element 
    facList= []
    for f, e in facs:
        num = _sage_const_1 
        for i in srange(e):
            num *= f
        facList.append(num)
    #lets rename the list of a's too
    A = bits
    print("Applying Sun Tzu's theorem...")
    #Now apply the chinese remainder theorem
    mTotal = _sage_const_1 
    for fac in facList:
        mTotal *= fac
    M = []
    for fac in facList:
        M.append(mTotal//fac)
    X = []
    for i,m in enumerate(M):
        x = inverse_mod(m,facList[i])
        X.append(x)
    res = _sage_const_0 
    for i in range(len(X)):
        res += (A[i] * X[i] * M[i]) % mTotal
        res = res % mTotal
    return res
    
def testing_ph():
    print("Answer: ",pohlig_hellman(_sage_const_1019 , _sage_const_7 , _sage_const_1001 ))   # 590
    print("===============================")
    print("Answer: ",pohlig_hellman(_sage_const_1879 , _sage_const_11 , _sage_const_1236 ))  # 1852
    print("===============================")
    print("Answer: ",pohlig_hellman(_sage_const_2029 , _sage_const_2 , _sage_const_819 ))    # 41
    print("===============================")
    print("Answer: ",pohlig_hellman(_sage_const_160079 ,_sage_const_17 ,_sage_const_66133 )) # 16744
    print("===============================")
    print("Answer: ",pohlig_hellman(_sage_const_161386420777 ,_sage_const_10 ,_sage_const_148775913664 )) # 28165436364
    print("===============================")
    print("Answer: ",pohlig_hellman(_sage_const_599939 , _sage_const_2 , _sage_const_93522 )) # 226948
    print("===============================")

        
#testing_ph()

print("Answer: ",pohlig_hellman(_sage_const_10192004369 , _sage_const_3  , _sage_const_7198247104 )) 
#print("Answer: ",pohlig_hellman(14400000337,5,9370058779)) # 7921731534 
#print("Answer: ",pohlig_hellman(4238338164061,6,3689495385185)) # 2430808064962 1.3 minutes
#print("Answer: ",pohlig_hellman(102092514301,10,30246603389)) # 55166371790  17.4 seconds
#print("Answer: ",pohlig_hellman(641617368221,2,472374485029)) # 610027025421 1.3 seconds
#print("Answer: ",pohlig_hellman(12600001177,17,11240688171)) # 9876543210  8.03 minutes
print("===============================")
#print("Answer: ",pohlig_hellman(21600000503, 5, 15151854931))
#print("===============================")

