

# This file was *autogenerated* from the file pollard_p.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_17 = Integer(17); _sage_const_7 = Integer(7); _sage_const_16 = Integer(16); _sage_const_107 = Integer(107); _sage_const_4 = Integer(4); _sage_const_83 = Integer(83); _sage_const_53 = Integer(53); _sage_const_133736723 = Integer(133736723); _sage_const_125783745 = Integer(125783745); _sage_const_133736722 = Integer(133736722); _sage_const_752557046340383 = Integer(752557046340383); _sage_const_84483694178164 = Integer(84483694178164); _sage_const_295976407848672 = Integer(295976407848672); _sage_const_376278523170191 = Integer(376278523170191)# just to make it easier to implement Floyds'
class traverser:
    def __init__(self,G: int,B: int,C: int):
        self.G = G
        self.B = B
        self.C = C
    def next(self, p: int, g: int, h: int, ell: int):
        if (self.G % _sage_const_3 ) == _sage_const_0 :
                self.B = (self.B + _sage_const_1 ) % ell
                self.G = (self.G * g) % p
        elif (self.G % _sage_const_3 ) == _sage_const_1 :
                self.C = (self.C + _sage_const_1 ) % ell
                self.G = (self.G * h) % p
        elif (self.G % _sage_const_3 ) == _sage_const_2 :
                self.B = (self.B * _sage_const_2 ) % ell
                self.C = (self.C * _sage_const_2 ) % ell
                self.G = (self.G * self.G) % p
        return self
            

def pollard_rho(p:int, g: int, h: int, ell: int) -> int:
    #
    G0, B0, C0 = g, _sage_const_1 , _sage_const_0 

    # also known as tortoise and hare
    walker = traverser(G0,B0,C0)
    runner = traverser(G0,B0,C0)

    walker = walker.next(p,g,h,ell)
    runner = runner.next(p,g,h,ell).next(p,g,h,ell)
    
    while(walker.G != runner.G) :
        walker = walker.next(p,g,h,ell)
        runner = runner.next(p,g,h,ell).next(p,g,h,ell)

    if(gcd(walker.C - runner.C,ell) != _sage_const_1 ):
        print("No inverse exists.. cant produce an answer currently..")
        return -_sage_const_1 
    solution = ((runner.B - walker.B)* inverse_mod((walker.C - runner.C),ell)) % ell
    return solution 

print("Answer: ", pollard_rho(_sage_const_17 ,_sage_const_3 ,_sage_const_7 ,_sage_const_16 ))
print("===============================")
print("Answer: ", pollard_rho(_sage_const_107 ,_sage_const_4 ,_sage_const_83 ,_sage_const_53 ))
print("===============================")
print("Answer: ", pollard_rho(_sage_const_133736723 ,_sage_const_2 ,_sage_const_125783745 ,_sage_const_133736722 )) # 29991398 inverse mod !
print("===============================")
print("Answer: ", pollard_rho(_sage_const_752557046340383 ,_sage_const_84483694178164 ,_sage_const_295976407848672 ,_sage_const_376278523170191 ))
print("===============================")
print("Answer: ", pollard_rho(_sage_const_133736723 ,_sage_const_2 ,_sage_const_125783745 ,_sage_const_133736722 ))
print("===============================")

