

# This file was *autogenerated* from the file elGamal_attack.sage
from sage.all_cmdline import *   # import sage library

_sage_const_555 = Integer(555); _sage_const_1 = Integer(1)
load("eg_sign.sage")
load("../algorithms/pohlig_hellman.sage")

m = _sage_const_555 
r,sig = oracle(m)

r = ZZ(r)
while gcd(r,p-_sage_const_1 ) != _sage_const_1 :
    r,sig = oracle(m)
    r = ZZ(r)
k = pohlig_hellman(p,g,r)

r_inv = inverse_mod(r,p-_sage_const_1 )
a =  ((m - (sig * k)) * r_inv) % (p-_sage_const_1 )
print("THE key is:",a)

