

# This file was *autogenerated* from the file DH_Fq.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_10 = Integer(10); _sage_const_9 = Integer(9); _sage_const_8 = Integer(8); _sage_const_7 = Integer(7); _sage_const_6 = Integer(6); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_3 = Integer(3); _sage_const_1 = Integer(1)
p = _sage_const_2 
q = _sage_const_10 
w = PolynomialRing(GF(p), 'x')
x = w.gen()
f = x**_sage_const_10  + x**_sage_const_9  + x**_sage_const_8  + x**_sage_const_7  + x**_sage_const_6  + x**_sage_const_5  + x**_sage_const_4  + x**_sage_const_3  + x**_sage_const_2  + x**_sage_const_1  +_sage_const_1 

Fq = GF(p**q, 'a', modulus=f)
a = Fq.gen() 
g = a**_sage_const_9  + a**_sage_const_5  + a**_sage_const_4  + a**_sage_const_3  + _sage_const_1 

class exchangers:
    def __init__(self):
        n = randint(_sage_const_2 ,(p**q)-_sage_const_2 )
        gn = g**n
        self.sK = n
        self.pK = gn
        self.sharedKey = None
    def send(self):
        return self.pK

    def recieve(self,pK):
        self.sharedKey = pK**self.sK
    
    def __str__(self):
        s1 = "sK: " + str(self.sK) +"\n"
        s2 = "pK: " + str(self.pK) +"\n"
        s3 = "shared secret: : " + str(self.sharedKey) +"\n"
        return s1 + s2 + s3


def DiffieHellman_Fq():
    diffie = exchangers()
    hellman = exchangers()
    
    diffie_pk = diffie.send() 
    hellman.recieve(diffie_pk)
    hellman_pk = hellman.send()
    diffie.recieve(hellman_pk)
    
    assert hellman.sharedKey == diffie.sharedKey
    print("diffie: ",str(diffie))
    print("======================")
    print("hellman: ",str(hellman))

DiffieHellman_Fq()

