

# This file was *autogenerated* from the file index_calc.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_10 = Integer(10); _sage_const_5 = Integer(5); _sage_const_0 = Integer(0); _sage_const_4238338164061 = Integer(4238338164061); _sage_const_6 = Integer(6); _sage_const_3689495385185 = Integer(3689495385185); _sage_const_102092514301 = Integer(102092514301); _sage_const_30246603389 = Integer(30246603389); _sage_const_641617368221 = Integer(641617368221); _sage_const_472374485029 = Integer(472374485029); _sage_const_12600001177 = Integer(12600001177); _sage_const_17 = Integer(17); _sage_const_11240688171 = Integer(11240688171); _sage_const_950603238735531779 = Integer(950603238735531779); _sage_const_425904671921435603 = Integer(425904671921435603)
def IC(p: int, g: int, h: int)->int:

    order = ZZ(p-_sage_const_1 )
    B = e**(_sage_const_1 /_sage_const_2  * (sqrt(ln(order) * ln(ln(order)))))
    B = min(B,_sage_const_10 **_sage_const_5 )
    
    P = Primes()
    factor_base = set()
    i = _sage_const_1 
    while len(factor_base) < B:
        factor_base.add(P.next(i))
        i += _sage_const_1 

    relations = []
    exponents = [] #gonna be a list of lists
    while len(relations)!= len(factor_base)+_sage_const_10 :
        k = randint(_sage_const_1 ,p-_sage_const_2 )        

        factors = []
        y = power_mod(g,k,p)
        for fac in factor_base:
            exponent = _sage_const_0 
            while fac.divides(y):
                y = y // fac
                exponent += _sage_const_1 
            factors.append(exponent)
        if y == _sage_const_1 :
            relations.append(k)
            exponents.append(factors)
    relations = vector(Integers(order),relations)
    exponents = matrix(Integers(order),exponents)
    solved_logs = exponents.solve_right(relations)
    exponents = [] 
    while True:
        factors = []
        k = randint(_sage_const_1 ,p-_sage_const_2 )
        y = (power_mod(g,k,p) * h) % p
        for fac in factor_base:
            exponent = _sage_const_0 
            while fac.divides(y):
                y = y // fac
                exponent += _sage_const_1 
            factors.append(exponent)
        if y == _sage_const_1 :
            exponents = factors
            break
    exponents = vector(Integers(order),exponents)
    sol = ((solved_logs.dot_product(exponents)) - k) % order
    if power_mod(g,sol,p) != h % p:
        return -_sage_const_1 
    return ZZ(sol)

# This function repeats running index calclus in case it fails, until success
def recursive_IC(p: int, g: int, h: int):
    while (res := IC(p,g,h)) == -_sage_const_1 :
        continue
    return res
        
                
                
#print("Answer: ",IC(1879, 11, 1236))  # 1852
#print("===============================")
#print("Answer: ",IC(161386420777,10,148775913664)) # 28165436364
#print("===============================")
#print("Answer: ",IC(599939, 2, 93522)) # 226948


#for i in range(25):
#    print("Answer: ",recursive_IC(161386420777,10,148775913664)) # 28165436364
    
print("Answer: ",recursive_IC(_sage_const_4238338164061 ,_sage_const_6 ,_sage_const_3689495385185 )) # 2430808064962 
print("Answer: ",recursive_IC(_sage_const_102092514301 ,_sage_const_10 ,_sage_const_30246603389 )) # 55166371790  
print("Answer: ",recursive_IC(_sage_const_641617368221 ,_sage_const_2 ,_sage_const_472374485029 )) # 610027025421 
print("Answer: ",recursive_IC(_sage_const_12600001177 ,_sage_const_17 ,_sage_const_11240688171 )) # 9876543210  
print("Answer: ",recursive_IC(_sage_const_950603238735531779 ,_sage_const_2 ,_sage_const_425904671921435603 )) # 502937120854632774  

